### ISSUE TITLE
Environment configuration issues have been resolved

### ISSUE THREAD

**Issue by 3BPM** [bytedance/DEADiff#21]
1.缺少onnxruntime-gpu
requirements.txt中改为
onnxruntime-gpu==1.11.0
2.缺少lavis
pip install salesforce-lavis之后会覆盖安装opencv，于是再安装opencv-python-headless==4.6.0.66，即可成功复现。

**Comment by c-q1218** [comment]
Traceback (most recent call last):
  File "xxxx/DEADiff-main/inference.py", line 8, in <module>
    import torch
  File "/root/miniconda3/envs/deadiff/lib/python3.9/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /root/miniconda3/envs/deadiff/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
